### PR TITLE
Arm

### PR DESCRIPTION
**Pull request by flackdl**
I just copied your `Dockerfile` but based the image off [alpine-arm](https://hub.docker.com/r/easypi/alpine-arm/).  It sucks to just copy the entire thing to only have one difference, but I don't know how else to do it.

### CODE REVIEW

**Comment by jnovack** [comment]
Is [this](https://github.com/jnovack/docker-rpi-autossh) what you wanted?

**Comment by flackdl** [comment]
Aha! I didn't see that.  Thanks, that's perfect.

**Comment by jnovack** [comment]
No problem at all.  I had to separate it so that it would build separately on Docker Hub.  I suppose I should add some links.

**Comment by flackdl** [comment]
Yes, it's too bad you can't specify separate build files in git for Docker Hub.  Well, thanks for the repos, they're trimmed down and perfect :+1:

**Pull request closed without merging**
